In [1]:
import torch
import torch.distributions as dist

In [2]:
# Lets create a Bernoulli distribution

bernoulli = dist.Bernoulli(torch.tensor([0.5]))

# Sample from the distribution
for _ in range(10):
    print(bernoulli.sample())

tensor([0.])
tensor([1.])
tensor([0.])
tensor([1.])
tensor([1.])
tensor([0.])
tensor([1.])
tensor([1.])
tensor([1.])
tensor([0.])


In [3]:
samples = [bernoulli.sample() for _ in range(1000)]
print(f"Mean: {torch.mean(torch.stack(samples))}")
print(f"Variance: {torch.var(torch.stack(samples))}")

Mean: 0.5120000243186951
Variance: 0.2501060962677002


In [4]:
# Lets create a Normal distribution
normal = dist.Normal(torch.tensor([0.0]), torch.tensor([1.0]))
for _ in range(10):
    print(normal.sample())

tensor([-0.1353])
tensor([-0.6653])
tensor([-1.2100])
tensor([-0.8939])
tensor([0.3342])
tensor([-0.4296])
tensor([1.7776])
tensor([0.4482])
tensor([0.2907])
tensor([0.8252])


In [7]:
samples = [normal.sample() for _ in range(1000)]
print(f"Mean: {torch.mean(torch.stack(samples))}")
print(f"Variance: {torch.var(torch.stack(samples))}")

Mean: 0.05843529850244522
Variance: 1.0243332386016846
