In [1]:
# Imports
import torch

In [19]:
# Let's create a new tensor and use requires_grad=True
# grad true means it is doing back propagation and it will calculate the gradients for us
#y = torch.rand(10)
a = torch.rand(10, requires_grad=True)
a


tensor([0.0602, 0.7383, 0.3560, 0.5724, 0.5468, 0.4104, 0.7333, 0.3355, 0.4787,
        0.4545], requires_grad=True)

In [20]:
# Let's build up a computation graph
# notice how this tensor had a special function called grad_fn

b = (a ** 2).mean()
b

tensor(0.2557, grad_fn=<MeanBackward0>)

In [21]:
# Lets compute one more tensor
c = b.mean()
c

tensor(0.2557, grad_fn=<MeanBackward0>)

In [22]:
# Since this is a scalar we can call backward on it
c.backward()
print(c)

tensor(0.2557, grad_fn=<MeanBackward0>)


In [ ]:
# Now we can see the gradients of a
print(a/10*2) # 1/10 comes from the mean and 2 comes from the power of 2
print(a.grad)

tensor([0.0120, 0.1477, 0.0712, 0.1145, 0.1094, 0.0821, 0.1467, 0.0671, 0.0957,
        0.0909], grad_fn=<MulBackward0>)
tensor([0.0120, 0.1477, 0.0712, 0.1145, 0.1094, 0.0821, 0.1467, 0.0671, 0.0957,
        0.0909])


In [ ]:

torch.cuda.memory_allocated()

In [ ]:

a = torch.rand(2**20, requires_grad=True, device="cuda")
torch.cuda.memory_allocated() / 1024.0**2

In [ ]:
b = torch.relu(a)
torch.cuda.memory_allocated() / 1024.0**2

In [ ]:

b = a
for _ in range(100):
    b = torch.relu(b)
torch.cuda.memory_allocated() / 1024.0**2

In [ ]:

b.sum().backward()
torch.cuda.memory_allocated() / 1024.0**2

In [ ]:
a.grad