In [ ]:
#   title: Loss Functions in PyTorch

In [1]:
import torch

In [2]:
model = torch.nn.Linear(10, 1)

In [3]:
x = torch.randn(20, 10)
y = torch.randn(20, 1)
print(f'{x=}{y=}')

x=tensor([[-0.6595,  0.4010, -0.9710, -0.0531, -1.3736,  0.1786,  0.1115,  0.4110,
         -1.7975,  0.7386],
        [-1.3655, -0.0060, -0.1268, -1.3449,  0.3782, -0.8392,  1.7163, -1.1920,
         -0.7812, -0.4544],
        [ 0.6533, -0.6769,  1.4791, -0.9659,  1.1961, -1.3208, -0.2002,  0.6141,
         -0.6965, -0.3473],
        [-0.6228,  0.8245,  0.2538,  0.8078,  0.2092, -0.1008,  0.2017, -2.3540,
          1.1899,  0.2927],
        [ 0.3245,  1.6127, -0.7958, -0.3718, -1.1039, -0.1416,  0.8570, -0.3813,
          0.0459, -0.8943],
        [-1.2246,  0.3898,  0.4010, -0.7401,  1.4525, -0.0779,  1.4010,  0.1019,
         -0.1632,  0.2304],
        [ 0.4447, -0.8528,  1.7382,  1.0072, -1.2111, -2.2184, -0.6657,  0.0792,
          1.2389, -0.8144],
        [ 0.1564, -2.1224,  1.1831,  1.8314, -0.0894,  0.4541, -0.7623,  0.8100,
          0.8058,  0.9166],
        [ 0.5888, -0.7657,  0.5662,  0.8560, -1.9039,  0.4293,  1.5294,  1.1681,
          0.1999,  0.1469],
        [-0.5265,

In [5]:
pred_y = model(x)
print(pred_y)

tensor([[ 0.6555],
        [ 0.2013],
        [-0.3078],
        [-0.2716],
        [ 0.8915],
        [ 0.0397],
        [ 0.2197],
        [-0.1681],
        [ 1.1065],
        [ 0.1886],
        [-0.1332],
        [ 0.5085],
        [ 0.9387],
        [ 0.4942],
        [-0.0192],
        [ 0.8833],
        [-0.2399],
        [-0.4989],
        [-0.0349],
        [ 0.6578]], grad_fn=<AddmmBackward0>)


In [10]:
#compare y and pred_y
loss = torch.nn.functional.mse_loss(pred_y, y)
print(loss)
#loss = loss_fn(pred_y, y)

tensor(1.2741, grad_fn=<MseLossBackward0>)


In [ ]:
#actual breakdown of the calculation from above function
def mse_loss(pred_y, y):
    return torch.mean((pred_y - y) ** 2)
mse_loss(pred_y, y)

tensor(1.2741, grad_fn=<MeanBackward0>)

In [ ]:
#binary loss

y = (torch.randn(20, 1) > 0).float()
print(y)

tensor([[0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.]])


In [ ]:
#adds sigmoid for us - do not add it ourselves
#.7 is essentially random so 50/50 chance gets .7
# less than .7 is better than random, more than .7 is worse than random

loss = torch.nn.functional.binary_cross_entropy_with_logits(pred_y, y)
print(loss)

tensor(0.7737, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)


In [20]:
#multiclass loss
#change number of outputs to 3 for 3 classes
n_classes = 3
model = torch.nn.Linear(10, n_classes)
y = (torch.randn(20) > 0).long() + (torch.randn(20) > 0).long()
print(y)

tensor([2, 2, 0, 0, 2, 0, 0, 1, 2, 1, 2, 1, 0, 1, 1, 2, 1, 0, 0, 1])


In [21]:
pred_y = model(x)
loss = torch.nn.functional.cross_entropy(pred_y, y)
print(loss)

tensor(1.1216, grad_fn=<NllLossBackward0>)


In [ ]:
#below is original professor code.

In [ ]:
import torch

# example of l2 loss function for linear regression


def l2_loss(y_true, y_pred):
    return torch.sum((y_true - y_pred) ** 2)


linear = torch.nn.Linear(4, 1)
x = torch.rand((1, 4))

y_true = torch.as_tensor([1.0], dtype=torch.float32)
y_pred = linear(x)

print(l2_loss(y_true, y_pred))

In [ ]:
import torch

# example of binary cross entropy loss function for binary classification

linear = torch.nn.Linear(4, 1)
x = torch.rand((1, 4))

y_true = torch.as_tensor([[1]], dtype=torch.float32)

y_pred = torch.sigmoid(linear(x))

loss_func = torch.nn.BCELoss()

print(loss_func(y_pred, y_true))

In [ ]:
import torch

# example of multi-class cross entropy loss function for multi-class classification

num_class = 3

linear = torch.nn.Linear(4, num_class)
x = torch.rand((1, 4))

y_true = torch.as_tensor([2], dtype=torch.int64)

y_pred = linear(x)

loss_func = torch.nn.CrossEntropyLoss()

print(loss_func(y_pred, y_true))