In [1]:
import torch
import torch.nn as nn

In [12]:
linear = torch.nn.Linear(10, 1)


In [6]:
print(linear)
print(linear.weight)
print(linear.bias)

Linear(in_features=10, out_features=1, bias=True)
Parameter containing:
tensor([[-0.0979, -0.2534,  0.1894,  0.2920,  0.1634,  0.2726,  0.1141, -0.1446,
          0.2069,  0.1651]], requires_grad=True)
Parameter containing:
tensor([-0.1111], requires_grad=True)


In [13]:
x = torch.ones(10)
linear(x)

tensor([0.6024], grad_fn=<ViewBackward0>)

In [14]:
x = torch.zeros(10)
linear(x)

tensor([-0.3092], grad_fn=<ViewBackward0>)

In [ ]:
linear = torch.nn.Linear(10, 1)
print(f"{linear.weight=}")
print(f"{linear.bias=}")
x = torch.as_tensor([1, 2, 3, 4], dtype=torch.float32)
print(f"{linear(x)=}")