In [ ]:
#binary puts it in 2 classifications (usually 0 and 1)
#based on percentage that it is in one class or the other

In [ ]:
#sigma x function is the sigmoid function
#sigmoid function is used to convert the output of a linear model into a probability between 0 and 1
#sigmoid function is defined as 1 / (1 + e^(-x))
#where x is the output of the linear model (the weighted sum of the inputs)
#binary linear function is sigmoid(W * x + b)
#So take linear and mutilply it by sigmoid to get the output of the model in the range of 0 to 1 (binary)

In [1]:
import torch
import torch.nn as nn

In [ ]:
class LinearClassifier(torch.nn.Module):
    def __init__(self, input_dim, output_dim):
        super().__init__()
        self.fc = torch.nn.Linear(input_dim, output_dim)

    def forward(self, x):
        return nn.functional.sigmoid(self.fc(x)) #never use this this!!!!! sigmoid should not be used directly
    
model = LinearClassifier(10, 1)
print(model)
print(model.fc.weight)
print(model.fc.bias)

#x= torch.zeros(10)
x=torch.ones(10)
model(x)


LinearClassifier(
  (fc): Linear(in_features=10, out_features=1, bias=True)
)
Parameter containing:
tensor([[ 0.2264, -0.1056, -0.0208, -0.3145, -0.2409, -0.2865, -0.0566, -0.0311,
         -0.1532, -0.0937]], requires_grad=True)
Parameter containing:
tensor([0.1865], requires_grad=True)


tensor([0.2911], grad_fn=<SigmoidBackward0>)

In [6]:
x=torch.rand(100,10)
model(x)

tensor([[0.4751],
        [0.3536],
        [0.4744],
        [0.4270],
        [0.4256],
        [0.3698],
        [0.3860],
        [0.3634],
        [0.4805],
        [0.4348],
        [0.3772],
        [0.3904],
        [0.4514],
        [0.3609],
        [0.3451],
        [0.4217],
        [0.3927],
        [0.3754],
        [0.4165],
        [0.4280],
        [0.4638],
        [0.4296],
        [0.4526],
        [0.4669],
        [0.4185],
        [0.4479],
        [0.3735],
        [0.4231],
        [0.4385],
        [0.4409],
        [0.4401],
        [0.4452],
        [0.4079],
        [0.3888],
        [0.3730],
        [0.4791],
        [0.3640],
        [0.4593],
        [0.3757],
        [0.3871],
        [0.4045],
        [0.4237],
        [0.3946],
        [0.3630],
        [0.3787],
        [0.3771],
        [0.4661],
        [0.4575],
        [0.4056],
        [0.3466],
        [0.3758],
        [0.3498],
        [0.3531],
        [0.4191],
        [0.5309],
        [0