In [ ]:
#multiclass classification
#softmax function 
#softmax = e(x) / sum(e^(x))
#creates multiple functions for each class. Input into each and the largest percentage indicates the class it would be for the output classification.


In [1]:
import torch
import torch.nn as nn

In [2]:
class LinearClassifier(torch.nn.Module):
    def __init__(self, input_dim, n_classes):
        super().__init__()
        self.fc = torch.nn.Linear(input_dim, n_classes)

    def forward(self, x):
        return nn.functional.softmax(self.fc(x), dim=-1) #SOFTMAX is the key point
    
model = LinearClassifier(10, 4)
print(model)
print(model.fc.weight)
print(model.fc.bias)

#x= torch.zeros(10)
x=torch.ones(10)
model(x)

LinearClassifier(
  (fc): Linear(in_features=10, out_features=4, bias=True)
)
Parameter containing:
tensor([[-0.2468, -0.1793,  0.0506,  0.2052, -0.3001, -0.2091, -0.0026,  0.0738,
          0.2135,  0.2647],
        [ 0.0131, -0.1840,  0.0120,  0.0012, -0.1954, -0.0580, -0.2139, -0.0910,
         -0.1109,  0.2688],
        [ 0.1091, -0.1330, -0.2401,  0.0313,  0.2062,  0.2616, -0.0531, -0.0500,
          0.1386,  0.0514],
        [-0.0346,  0.2586,  0.0480,  0.2049,  0.2796, -0.2472, -0.1748,  0.0058,
          0.0785, -0.2473]], requires_grad=True)
Parameter containing:
tensor([-0.2270, -0.1813, -0.2647,  0.2598], requires_grad=True)


tensor([0.1854, 0.1264, 0.2805, 0.4077], grad_fn=<SoftmaxBackward0>)