In [1]:
import torch

In [3]:
net1 = torch.nn.Sequential(
    torch.nn.Conv2d(1, 1, 3, stride=2, padding=1, dilation=1),
    torch.nn.ReLU(),
    torch.nn.Conv2d(1, 1, 3, stride=1, padding=1, dilation=1),
)
net2 = torch.nn.Sequential(
    torch.nn.Conv2d(1, 1, 3, stride=1, padding=1, dilation=1),
    torch.nn.ReLU(),
    torch.nn.Conv2d(1, 1, 3, stride=1, padding=2, dilation=2),
)
for p1, p2 in zip(net1.parameters(), net2.parameters()):
    p2.data = p1.data.clone()
    p2.requires_grad = True

x = torch.randn(1, 1, 5, 5)
print(x.shape, net1(x).shape)
print(x.shape, net2(x).shape)
y1 = net1(x)
y2 = net2(x)
print(y1)
print(y2)
print(y2[:, :, ::2, ::2])

torch.Size([1, 1, 5, 5]) torch.Size([1, 1, 3, 3])
torch.Size([1, 1, 5, 5]) torch.Size([1, 1, 5, 5])
tensor([[[[-0.2474, -0.2536, -0.2269],
          [-0.1974, -0.2679, -0.2269],
          [-0.2160, -0.2388, -0.2269]]]], grad_fn=<ConvolutionBackward0>)
tensor([[[[-0.2474, -0.5132, -0.2536, -0.5276, -0.2269],
          [-0.2269, -0.2875, -0.2269, -0.2727, -0.2269],
          [-0.1974, -0.3528, -0.2679, -0.2893, -0.2269],
          [-0.2269, -0.1796, -0.2269, -0.2686, -0.2269],
          [-0.2160,  0.0369, -0.2388, -0.5141, -0.2269]]]],
       grad_fn=<ConvolutionBackward0>)
tensor([[[[-0.2474, -0.2536, -0.2269],
          [-0.1974, -0.2679, -0.2269],
          [-0.2160, -0.2388, -0.2269]]]], grad_fn=<SliceBackward0>)


In [ ]:
net1 = torch.nn.Sequential(
    torch.nn.Conv2d(1, 1, 3, stride=2, padding=1, dilation=1),
    torch.nn.ReLU(),
    torch.nn.Conv2d(1, 1, 3, stride=1, padding=1, dilation=1),
    torch.nn.ReLU(),
    torch.nn.ConvTranspose2d(1, 1, 3, stride=2, padding=1, output_padding=1),
)

x = torch.randn(1, 1, 5, 5)
print(net1(x)[:, :, : x.shape[2], : x.shape[3]].shape)