In [1]:
import torch

In [2]:
a = torch.tensor([1, 2, 3], dtype=torch.float32)
print(a)

tensor([1., 2., 3.])


In [3]:
b = torch.rand([3, 3, 3], dtype=torch.float32)
print(b)

tensor([[[0.7749, 0.8381, 0.9508],
         [0.4925, 0.1006, 0.7517],
         [0.6143, 0.7654, 0.6918]],

        [[0.2003, 0.7475, 0.1919],
         [0.4851, 0.2343, 0.1108],
         [0.0241, 0.1252, 0.1336]],

        [[0.2492, 0.9894, 0.6856],
         [0.8094, 0.1922, 0.3369],
         [0.0580, 0.2129, 0.0843]]])


In [ ]:
import numpy as np
from PIL import Image

img = Image.open("cat.jpg")
#img
c = torch.as_tensor(np.array(img)).float() #as_tensor changes the data to a tensor  
print(c.dtype)
print(c.shape)
print(c)
#print(img)

torch.float32
torch.Size([350, 625, 3])
tensor([[[ 62.,  75.,  55.],
         [ 61.,  74.,  54.],
         [ 59.,  72.,  54.],
         ...,
         [138., 139., 141.],
         [138., 139., 141.],
         [138., 139., 141.]],

        [[ 63.,  76.,  56.],
         [ 62.,  75.,  55.],
         [ 60.,  73.,  55.],
         ...,
         [138., 139., 141.],
         [138., 139., 141.],
         [138., 139., 141.]],

        [[ 64.,  77.,  57.],
         [ 63.,  76.,  56.],
         [ 60.,  73.,  55.],
         ...,
         [138., 139., 141.],
         [137., 138., 140.],
         [138., 139., 141.]],

        ...,

        [[ 71.,  60.,  58.],
         [ 73.,  62.,  60.],
         [ 74.,  63.,  61.],
         ...,
         [215., 227., 239.],
         [215., 227., 239.],
         [214., 228., 241.]],

        [[ 79.,  65.,  64.],
         [ 80.,  66.,  65.],
         [ 80.,  69.,  67.],
         ...,
         [215., 227., 239.],
         [215., 227., 239.],
         [214., 228., 241.]

In [13]:
a = torch.arange(10)
b = torch.ones(10)
print(f"{a = }")
print(f"{b = }")
print(f"{a ** (2 * b) = }")

a = tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
b = tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
a ** (2 * b) = tensor([ 0.,  1.,  4.,  9., 16., 25., 36., 49., 64., 81.])


In [ ]:
a = torch.rand(4)
b = torch.rand(5)
# print(a + b)

In [ ]:
a = torch.rand(500_000_000)
b = torch.rand(500_000_000)
c = a + b

In [ ]:
%timeit c = a + b

In [ ]:
a_gpu = a.to("cuda")
b_gpu = b.to("cuda")
%timeit c_gpu = a_gpu + b_gpu

In [ ]:
a = torch.arange(6)
print(a.reshape(2, 3))

In [ ]:
a = torch.rand(2, 3, 4)
print(a.permute(1, 2, 0).shape)

In [ ]:
a = torch.arange(6).view(3, 2, 1, 1)
print(a.squeeze().shape)

In [ ]:
a = torch.arange(4).view(4, 1)
b = torch.arange(5).view(1, 5) * 10
print(f"{a = }")
print(f"{b = }")
print(a - b)

In [ ]:
x = torch.randn(10, 2)
d = torch.zeros(10, 10)
for i in range(10):
    for j in range(10):
        d[i, j] = (x[i] - x[j]).pow(2).sum()

d = (x[:, None, :] - x[None, :, :]).pow(2).sum(-1)

In [ ]:
x = torch.randn(10, 2)
d = torch.zeros(10, 10)
max_dist, max_idx = 0, (-1, -1)
for i in range(10):
    for j in range(10):
        if (x[i] - x[j]).pow(2).sum() > max_dist:
            max_dist, max_idx = (x[i] - x[j]).pow(2).sum(), (i, j)

print(max_dist, max_idx)

d = (x[:, None, :] - x[None, :, :]).pow(2).sum(-1)
print(d.max(), (d.argmax() // 10, d.argmax() % 10))

In [ ]:
a = torch.rand(2, 4)
b = torch.rand(4)
c = b @ a.mT
print(c.shape)
print(torch.linalg.norm(b))
# print(b.pow(2).sum().sqrt())